services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "6767:4533"
    environment:
      ND_MUSICFOLDER: "/music"
      ND_DATAFOLDER: "/data"
      ND_SCROBBLE: "true"
      ND_ENABLEPLAYLISTS: "true"
      ND_ENABLECORS: "true"
      ND_CORS_ALLOWEDORIGINS: "*"
      ND_ENABLEEXTERNALSERVICES: "true"
      ND_SPOTIFY_ID: "96edd1b3fccb44d3b260d47e6aba5d59"
      ND_SPOTIFY_SECRET: "a40b1758c7e945c0aa540fdfd5e7981c"
      ND_LASTFM_ENABLED: "true"
      ND_LASTFM_APIKEY: "8cd4f9a0768e6bb7cf406566a7803a01"
      ND_LASTFM_SECRET: "a5664985efd44e5cc350f24fd6d401f3"
    volumes:
      - ./navidrome-data:/data
      - ./my-music:/music:ro
  subsonic-player:
    image: vd39/subsonic-player:latest
    container_name: subsonic-player
    restart: unless-stopped
    ports:
      - "6969:3000"
    environment:
      - NUXT_PUBLIC_SERVER_URL=http://100.107.208.98:6767